FROM lmsysorg/sglang:latest

ENV HF_HUB_OFFLINE=1

CMD ["python", "-m", "sglang.launch_server", \
    "--model", "/app/models/qwen3-coder-next", \
    "--host", "0.0.0.0", \
    "--port", "8004", \
    "--dtype", "bfloat16", \
    "--served-model-name", "local", \
    "--tool-call-parser", "qwen3_coder" \
]
